### PR TITLE
Fix tag retrieval for Redis

### LINKED ISSUE #177: Redis Undefined offset: 1
Hello,

I am using WSL2 and I am getting an error when enabling Redis.

redis

Am I doing something wrong?

Thanks in advance

### PR DESCRIPTION
**Pull request by zoispag**
Fix tag retrieval for Redis

Closes #177

Tag for redis is not a semver string, but "buster", as in underlying debian version

### CODE REVIEW

File: app/Services/BaseService.php [hunk 1]
```diff
@@ -182,6 +182,10 @@ protected function buildParameters(): array
 
     protected function shortNameWithVersion(): string
     {
+        if (! preg_match('/v?(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*)))?)/', $this->tag)) {
```
Comment (mattstauffer) [inline app/Services/BaseService.php:185]: Would you mind leaving a comment here about what this is for? Thanks for the catch; I wish I had even thought of this!

Comment (zoispag) [reply app/Services/BaseService.php:187]: Done 👍🏼

File: app/Services/BaseService.php [hunk 2]
```diff
@@ -182,6 +182,8 @@ protected function buildParameters(): array
 
     protected function shortNameWithVersion(): string
     {
+        // Check if tag represents semantic version (v5.6.0, 5.7.4, or 8.0) and return major.minor
+        // (eg mysql5.7) or return the actual tag prefixed by a dash (eg redis-buster)
```
Comment (danielebarbaro) [inline app/Services/BaseService.php:186]: Chapeau.

**Comment by danielebarbaro** [comment]
@mattstauffer at the moment all services doesn't start without this PR :)

**Comment by mattstauffer** [comment]
Thanks  so much!

**Comment by mattstauffer** [comment]
@danielebarbaro Weird, they're all starting fine for me, but merging and pushing :D
